---

- name: Run show commands on routers
  hosts: cisco-routers

  tasks:

    - name: Ping host
      ios_command:
        commands: ping 192.168.100.100
        wait_for:
          - result[0] contains 'Success rate is 100 percent'
