---

- name: Run cfg commands on routers
  hosts: 192.168.100.1

  tasks:

    - name: Config interface
      ios_config:
        parents:
          - interface Ethernet0/2
        lines:
          - ip address 190.16.200.1 255.255.255.0
          - ip mtu 1500
        defaults: yes


