---

- name: Run cfg commands on router
  hosts: 192.168.100.1

  tasks:

    - name: Config interface
      ios_config:
        parents:
          - interface Ethernet0/3
        lines:
          - ip address 192.168.130.1 255.255.255.0
        after:
          - no shutdown
