---

- name: Run show commands on routers
  hosts: cisco_routers
  gather_facts: false

  tasks:

    - name: run sh commands
      ios_command:
        commands: 
          - sh arp
          - sh ip int br
      register: result

    - name: Debug output
      debug: var=result.stdout_lines
