---

- name: Collect IOS facts
  hosts: cisco-ios

  tasks:

    - name: Facts
      ios_facts:
        gather_subset: all
      register: ios_facts_result

    - name: Create all_facts dir
      file:
        path: ./all_facts/
        state: directory
        mode: 0755

    - name: Copy facts to files
      copy:
        content: "{{ ios_facts_result | to_nice_json }}"
        dest: "all_facts/{{inventory_hostname}}_facts.json"
